name: Autograding

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    if: github.actor != 'github-classroom[bot]'
    steps:
    - uses: actions/checkout@v3
    - name: setup environment
      run: |
        sudo apt-get update 
        sudo apt-get install valgrind -y 
        sudo apt-get install check
        pip3 install pyyaml
        mkdir build
    - name: build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake ..
        make
    - uses: education/autograding@v1
    
